Models/ViewModels/CierreProyectoView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using Prototipos.Models.DB;

namespace Prototipos.Models.ViewModels
{
    [Bind(Exclude = "IdPrototipo, Proyecto, Estado, IdUsuarioCierre")]
    public class CierreProyectoView
    {
        private PrototiposEntities entity = new PrototiposEntities();
        public CierreProyectoView() { }

        public CierreProyectoView(int id)
        {
            ProyectoActual = entity.tPrototipos.First(m => m.IdPrototipo == id);
            IdUsuarioCreador = ProyectoActual.IdUsuarioCreador;
            FechaCreacion = ProyectoActual.FechaCreacion;
            Responsable = ProyectoActual.Responsable;
            Configuracion = ProyectoActual.Configuracion;
            Descripcion = ProyectoActual.Descripcion;
            Observaciones = ProyectoActual.Observaciones;
            FechaCierre = ProyectoActual.FechaCierre;
            Cierre = ProyectoActual.Cierre;
        }

        public tPrototipo ProyectoActual { set; get; }

        [ScaffoldColumn(false)]
        public int IdPrototipo { get { return ProyectoActual.IdPrototipo; } set { ProyectoActual.IdPrototipo = value; } }

        [Display(Name = "Fecha creación:")]
        public DateTime FechaCreacion { get { return ProyectoActual.FechaCreacion; } set { ProyectoActual.FechaCreacion = value; } }

        [Display(Name = "Usuario creación:")]
        public string IdUsuarioCreador { get { return ProyectoActual.IdUsuarioCreador; } set { ProyectoActual.IdUsuarioCreador = value; } }

        [ScaffoldColumn(false)]
        public string Proyecto { get { return ProyectoActual.Proyecto; } set { ProyectoActual.Proyecto = value; } }

        [Display(Name = "Responsable I+D:")]
        public string Responsable { get { return ProyectoActual.Responsable; } set { ProyectoActual.Responsable = value; } }

        [Display(Name = "Configuración inicial del montaje:")]
        [DataType(DataType.MultilineText)]
        public string Configuracion { get { return ProyectoActual.Configuracion; } set { ProyectoActual.Configuracion = value; } }

        [Display(Name = "Descripción:")]
        [DataType(DataType.MultilineText)]
        public string Descripcion { get { return ProyectoActual.Descripcion; } set { ProyectoActual.Descripcion = value; } }

        [Display(Name = "Observaciones:")]
        [DataType(DataType.MultilineText)]
        public string Observaciones { get { return ProyectoActual.Observaciones; } set { ProyectoActual.Observaciones = value; } }

        [ScaffoldColumn(false)]
        public int Estado { get; set; }

        [Required(ErrorMessage = "Tiene que especificar una fecha de cierre")]
        [Display(Name = "Fecha cierre: (dd-mm-aaaa)")]
        [DisplayFormat(DataFormatString = "{dd-mm-yy}")]
        public DateTime? FechaCierre { get; set; }

        [ScaffoldColumn(false)]
        public string IdUsuarioCierre { get; set; }

        [Required(ErrorMessage = "Tiene que especificar observaciones de cierre del expediente")]
        [Display(Name = "Observaciones cierre del expediente:")]
        [StringLength(2500, ErrorMessage = "No puede exceder 2500 caracteres")]
        [DataType(DataType.MultilineText)]
        public string Cierre { get; set; }
    }
}

Models/ViewModels/DesbloqueoDefPruebaView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using Prototipos.Models.DB;

namespace Prototipos.Models.ViewModels
{
    [Bind(Exclude = "IdPrototipo, IdPrueba, IdDeficiencia, FechaRegistroDesbloqueo, IdUsuarioDesbloqueo, FechaRegistroResolucion")]
    public class DesbloqueoDefPruebaView
    {
        private PrototiposEntities entity = new PrototiposEntities();
        public DesbloqueoDefPruebaView() { }

        public DesbloqueoDefPruebaView(int id)
        {
            DefPruebaActual = entity.tDeficienciaPruebas.First(p => p.IdDeficiencia == id);
        }
        public tDeficienciaPrueba DefPruebaActual { get; set; }

        [ScaffoldColumn(false)]
        public int IdPrototipo { get { return DefPruebaActual.IdPrototipo; } set { DefPruebaActual.IdPrototipo = value; } }

        [ScaffoldColumn(false)]
        public int IdPrueba { get { return DefPruebaActual.IdPrueba; } set { DefPruebaActual.IdPrueba = value; } }

        [ScaffoldColumn(false)]
        public int IdDeficiencia { get { return DefPruebaActual.IdDeficiencia; } set { DefPruebaActual.IdDeficiencia = value; } }

        [Display(Name = "Fecha deficiencia:")]
        public DateTime Fecha { get { return DefPruebaActual.Fecha; } set { DefPruebaActual.Fecha = value; } }

        [Display(Name = "Usuario creación:")]
        public string IdUsuarioCreador { get { return DefPruebaActual.IdUsuarioCreador; } set { DefPruebaActual.IdUsuarioCreador = value; } }

        [Display(Name = "Descripción:")]
        public string Descripcion { get { return DefPruebaActual.Descripcion; } set { DefPruebaActual.Descripcion = value; } }

        [Display(Name = "Limitaciones:")]
        public string Limitaciones { get { return DefPruebaActual.Limitaciones; } set { DefPruebaActual.Limitaciones = value; } }

        [Display(Name = "Bloqueo del empleo del prototipo:")]
        public bool Bloqueo { get { return DefPruebaActual.Bloqueo; } set { DefPruebaActual.Bloqueo = value; } }

        [Required(ErrorMessage = "Tiene que especificar la fecha de desbloqueo")]
        [Display(Name = "Fecha de desbloqueo: (dd-mm-aaaa)")]
        [DisplayFormat(DataFormatString = "{dd-mm-yy}")]
        public DateTime? FechaDesbloqueo { get; set; }

        [ScaffoldColumn(false)]
        public DateTime FechaRegistroDesbloqueo { get; set; }

        [ScaffoldColumn(false)]
        public string IdUsuarioDesbloqueo { get; set; }

        [Display(Name = "Usuario bloqueo:")]
        public string IdUsuarioBloqueo { get { return DefPruebaActual.IdUsuarioBloqueo; } set { DefPruebaActual.IdUsuarioBloqueo = value; } }

        [Required(ErrorMessage = "Tiene que añadir las razones para el desbloqueo")]
        [Display(Name = "Razones para el desbloqueo:")]
        [StringLength(2500, ErrorMessage = "No puede exceder 2500 caracteres")]
        [DataType(DataType.MultilineText)]
        public string RazonDesbloqueo { get; set; }

        [Display(Name = "Fecha resolución:")]
        public DateTime? FechaResolucion { get { return DefPruebaActual.FechaResolucion; } set { DefPruebaActual.FechaResolucion = value; } }

        [ScaffoldColumn(false)]
        public DateTime? FechaRegistroResolucion { get; set; }

        [Display(Name = "Usuario resolución:")]
        public string IdUsuarioResolucion { get { return DefPruebaActual.IdUsuarioResolucion; } set { DefPruebaActual.IdUsuarioResolucion = value; } }

        [Display(Name = "Observaciones resolución:")]
        public string ObservacionesResolucion { get { return DefPruebaActual.ObservacionesResolucion; } set { DefPruebaActual.ObservacionesResolucion = value; } }
    }
}

Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.DirectoryServices.AccountManagement;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Prototipos.Models.DB;
using Prototipos.Models.ViewModels;
using Prototipos.Models.ObjectManager;

namespace Prototipos.Controllers
{
    public class FilesController : Controller
    {
        PrototiposEntities dre = new PrototiposEntities();

        [Authorize(Roles = @"DOMINIO\GestionPrototipos")]
        public ActionResult ProyAdjuntar(int id)
        {
            ArchivosProyManager archProyManager = new ArchivosProyManager(id);
            var proyecto = archProyManager.ProyectoActual;
            ViewBag.Message = " al proyecto ";
            ViewBag.Message2 = proyecto.Proyecto;
            ViewBag.Message3 = "Seleccione el archivo a adjuntar:";
            ViewBag.idProy = id;
            ViewBag.ErrorMessage = TempData["ErrorMessage"];

            return View(archProyManager);
        }

        // POST: /Files/ProyAdjuntar
        [HttpPost]
        public ActionResult ProyAdjuntar(HttpPostedFileBase uploadFile, int id, string descrip)
        {
            ArchivosProyManager archProyManager = new ArchivosProyManager(id);
            if (descrip.Length > 50)
            {
                TempData["ErrorMessage"] = "La descripción no puede tener más de 50 caracteres";
                return RedirectToAction("ProyAdjuntar", new { id = id });
            }
            else
            {
                archProyManager.AddArch(id);
                if (uploadFile != null && uploadFile.ContentLength > 0)
                {
                    var ultArch = (from a in dre.tPrototipoArchivos
                                   where a.IdPrototipo == id
                                   orderby a.FechaAdd descending
                                   select a).First();
                    int ultArchId = ultArch.IdArch;
                    archProyManager.SaveArch(id, ultArchId, uploadFile, descrip);
                }
                return RedirectToAction("GestionProyecto", "Home", new { id = id });
            }
        }

        [Authorize(Roles = @"DOMINIO\GestionPrototipos")]
        public ActionResult ProyAdjuntarYCerrar(int id)
        {
            ArchivosProyManager archProyManager = new ArchivosProyManager(id);
            var proyecto = archProyManager.ProyectoActual;
            ViewBag.Message = " al proyecto ";
            ViewBag.Message2 = proyecto.Proyecto;
            ViewBag.Message3 = "Seleccione el archivo a adjuntar:";
            ViewBag.idProy = id;
            ViewBag.ErrorMessage = TempData["ErrorMessage"];

            return View(archProyManager);
        }

        // POST: /Files/ProyAdjuntarYCerrar
        [HttpPost]
        public ActionResult ProyAdjuntarYCerrar(HttpPostedFileBase uploadFile, int id, string descrip)
        {
            ArchivosProyManager archProyManager = new ArchivosProyManager(id);
            if (descrip.Length > 50)
            {
                TempData["ErrorMessage"] = "La descripción no puede tener más de 50 caracteres";
                return RedirectToAction("ProyAdjuntar", new { id = id });
            }
            else
            {
                archProyManager.AddArch(id);
                if (uploadFile != null && uploadFile.ContentLength > 0)
                {
                    var ultArch = (from a in dre.tPrototipoArchivos
                                   where a.IdPrototipo == id
                                   orderby a.FechaAdd descending
                                   select a).First();
                    int ultArchId = ultArch.IdArch;
                    archProyManager.SaveArch(id, ultArchId, uploadFile, descrip);
                }
                return View("Close");
            }
        }

        [Authorize(Roles = @"DOMINIO\GestionPrototipos")]
        public ActionResult VerArchivoProy(int id)
        {
            var archivo = dre.tPrototipoArchivos.First(m => m.IdArch == id);

            MemoryStream ms = new MemoryStream(archivo.Contenido, 0, 0, true, true);
            Response.ContentType = archivo.Tipo;
            Response.AddHeader("content-disposition", "attachment;filename=" + Path.GetFileName(archivo.Nombre));
            Response.Buffer = true;
            Response.Clear();
            Response.OutputStream.Write(ms.GetBuffer(), 0, ms.GetBuffer().Length);
            Response.OutputStream.Flush();
            Response.End();
            return new FileStreamResult(Response.OutputStream, archivo.Tipo);
        }

        [Authorize(Roles = @"DOMINIO\GestionPrototipos")]
        public ActionResult EliminarArchivoProy(int id)
        {
            var archivo = dre.tPrototipoArchivos.First(m => m.IdArch == id);
            var proy = dre.tPrototipos.First(p => p.IdPrototipo == archivo.IdPrototipo);

            var context = new PrincipalContext(System.DirectoryServices.AccountManagement.ContextType.Domain);
            var user = System.Web.HttpContext.Current.User.Identity.Name;
            var usuario = UserPrincipal.FindByIdentity(context, user);
            var nombreUsuario = String.Concat(usuario.GivenName, " ", usuario.Surname);

            if (archivo.UsuarioAdd == nombreUsuario || proy.IdUsuarioCreador == user || proy.Responsable == user)
            {
                ViewBag.idArchivo = archivo.IdArch;
                ViewBag.IdProy = archivo.IdPrototipo;

                return View();
            }
            else
            {
                TempData["ErrorMessage"] = "Solo puede eliminar el archivo el que lo ha subido o el creador o responsable del proyecto";
                return RedirectToAction("GestionProyecto", "Home", new { id = archivo.IdPrototipo });
            }

        }

        [Authorize(Roles = @"DOMINIO\GestionPrototipos")]
        public ActionResult DeleteFileProy(int id)
        {
            var archivo = dre.tPrototipoArchivos.First(m => m.IdArch == id);
            int idPrototipo = archivo.IdPrototipo;
            ArchivosProyManager archProyManager = new ArchivosProyManager(idPrototipo);
            archProyManager.DelArch(id);

            return RedirectToAction("GestionProyecto", "Home", new { id = idPrototipo });
        }

        [Authorize(Roles = @"DOMINIO\GestionPrototipos")]
        public ActionResult MontajeAdjuntar(int id)
        {
            ArchivosManager archManager = new ArchivosManager(id);
            var proyecto = dre.tPrototipos.FirstOrDefault(f => f.IdPrototipo == archManager.FaseActual.IdPrototipo);
            ViewBag.Message = " al montaje del proyecto ";
            ViewBag.Message2 = proyecto.Proyecto;
            ViewBag.Message3 = "Seleccione el archivo a adjuntar:";
            ViewBag.idProy = archManager.FaseActual.IdPrototipo;
            ViewBag.ErrorMessage = TempData["ErrorMessage"];

            return View(archManager);
        }

        // POST: /Files/MontajeAdjuntar
        [HttpPost]
        public ActionResult MontajeAdjuntar(HttpPostedFileBase uploadFile, int id, string descrip)
        {
            ArchivosManager archManager = new ArchivosManager(id);
            if (descrip.Length > 50)
            {
                TempData["ErrorMessage"] = "La descripción no puede tener más de 50 caracteres";
                return RedirectToAction("MontajeAdjuntar", new { id = id });
            }
            else
            {
                archManager.AddArch(id);
                if (uploadFile != null && uploadFile.ContentLength > 0)
                {
                    var ultArch = (from a in dre.tFaseArchivos
                                   where a.IdFase == id
                                   orderby a.FechaAdd descending
                                   select a).First();
                    int ultArchId = ultArch.IdArch;
                    archManager.SaveArch(id, ultArchId, uploadFile, descrip);
                }
                return RedirectToAction("MontajeArchivos", new { id = id });
            }
        }

        [Authorize(Roles = @"DOMINIO\GestionPrototipos")]
        public ActionResult MontajeArchivos(int id)
        {
            ArchivosManager archManager = new ArchivosManager(id);
            if (archManager.TieneArchFase(id))
            {
                ViewBag.idFase = id;
                ViewBag.idProy = archManager.FaseActual.IdPrototipo;
                ViewBag.ErrorMessage = TempData["ErrorMessage"];
                return View(archManager);
            }
            else
            {
                TempData["ErrorMessage"] = "Este montaje no tiene archivos adjuntos";
                return RedirectToAction("Montaje", "Home", new { id = archManager.FaseActual.IdPrototipo });
            }
        }

        [Authorize(Roles = @"DOMINIO\GestionPrototipos")]
        public ActionResult VerArchivo(int id)
        {
            var archivo = dre.tFaseArchivos.First(m => m.IdArch == id);

            MemoryStream ms = new MemoryStream(archivo.Contenido, 0, 0, true, true);
            Response.ContentType = archivo.Tipo;
            Response.AddHeader("content-disposition", "attachment;filename=" + Path.GetFileName(archivo.Nombre));
            Response.Buffer = true;
            Response.Clear();
            Response.OutputStream.Write(ms.GetBuffer(), 0, ms.GetBuffer().Length);
            Response.OutputStream.Flush();
            Response.End();
            return new FileStreamResult(Response.OutputStream, archivo.Tipo);
        }

        [Authorize(Roles = @"DOMINIO\GestionPrototipos")]
        public ActionResult EliminarArchivoFase(int id)
        {
            var archivo = dre.tFaseArchivos.First(m => m.IdArch == id);
            var fase = dre.tFases.First(m => m.IdFase == archivo.IdFase);
            var proy = dre.tPrototipos.First(p => p.IdPrototipo == fase.IdPrototipo);

Views/Home/Cierre.cshtml
@model IEnumerable<Prototipos.Models.DB.tPrototipo>

@{
    Layout = "~/Views/Shared/_Layout3.cshtml";
    ViewBag.Title = "Cierre";

    WebGrid grid = new WebGrid(Model, selectionFieldName: "selectedRow", rowsPerPage: 10);
}

<div class="message-error">
    @ViewBag.ErrorMessage
</div>

<div class="center">
    <div class="title">
        <h1>@ViewBag.Title</h1>
        <h2>@ViewBag.Message</h2>
        <h3>Busque y/o seleccione el proyecto que desea cerrar:</h3>
    </div>
    <br />

    @using (Html.BeginForm("Cierre", null, FormMethod.Get))
    {    
        <h5> Proyecto: @Html.TextBox("SearchString") 
        <input type="submit" value="Buscar" /></h5> 
    } 
    <br />
    <div id="myGrid">
        @grid.GetHtml(
            fillEmptyRows: true,
            mode: WebGridPagerModes.All,
            rowStyle: "fila-normal",
            alternatingRowStyle: "fila-alternativa",
            selectedRowStyle: "fila-seleccionada",
            tableStyle: "tabla-grid",
            headerStyle: "encabezado-grid",
            footerStyle: "pie-grid",
            firstText: "<< Primera",
            previousText: "< Anterior",
            nextText: "Siguiente >",
            lastText: "Última >>",

            columns: new[] {
                grid.Column("Proyecto", header: "Proyecto", style: "pro",
                                        format: (item) => item.GetSelectLink(item.Proyecto)),
                grid.Column("FechaCreacion", header: "Fecha creación", style: "fechCi", 
                                          format: (item) => item.FechaCreacion != null ? item.FechaCreacion.ToString("dd-MM-yyyy") : ""),
                grid.Column("", header: "Opciones", style: "opcCi", 
                                format: @<text>
                                            @Html.ActionLink("Ver informe", "InformeProyecto", new { id = item.IdPrototipo }, new { target = "_blank" })
                                            |@Html.ActionLink(" Seleccionar", "CierreProyecto", new {id = item.IdPrototipo})
                                        </text>)
        })
    </div>
    <br />
</div>

Views/Home/CierreProyecto.cshtml
@model Prototipos.Models.ViewModels.CierreProyectoView

@{
    Layout = "~/Views/Shared/_Layout3.cshtml";
    ViewBag.Title = "Cierre";
}

<div class="title">
    <h1>@ViewBag.Title</h1>
    <h2>@ViewBag.Message <i>@ViewBag.Message2</i></h2>
</div>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>

        @Html.HiddenFor(m => m.ProyectoActual.IdPrototipo)
        @Html.HiddenFor(m => m.ProyectoActual.FechaCreacion)
        @Html.HiddenFor(m => m.ProyectoActual.IdUsuarioCreador)
        @Html.HiddenFor(m => m.ProyectoActual.Proyecto)
        @Html.HiddenFor(m => m.ProyectoActual.Responsable)
        @Html.HiddenFor(m => m.ProyectoActual.Configuracion)
        @Html.HiddenFor(m => m.ProyectoActual.Observaciones)
        @Html.HiddenFor(m => m.ProyectoActual.Estado)
        @Html.HiddenFor(m => m.ProyectoActual.IdUsuarioCierre)

        <div class="editor-label">
            @Html.LabelFor(model => model.FechaCreacion)
        </div>
        <div class="editor-ali">
            @Html.DisplayFor(model => model.FechaCreacion, "ShortDateTime")
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdUsuarioCreador)
        </div>
        <div class="editor-ali">
            @ViewBag.creador
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Descripcion)
        </div>
        <div class="editor-ali">
            @Model.Descripcion
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Responsable)
        </div>
        <div class="editor-ali">
            @ViewBag.Responsable
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Configuracion)
        </div>
        <div class="editor-ali">
            @Model.Configuracion
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Observaciones)
        </div>
        <div class="editor-ali">
            @Model.Observaciones
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FechaCierre)
        </div>
        <div class="editor-fecha">
            @Html.EditorFor(model => model.FechaCierre)
            @Html.ValidationMessageFor(model => model.FechaCierre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Cierre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Cierre)
            @Html.ValidationMessageFor(model => model.Cierre)
        </div>
        <br />
        <div class="center">
            <a href="@Url.Action("ProyAdjuntarYCerrar", "Files", new { id = ViewBag.idProy })" target="_blank" class="button6">Adjuntar un archivo</a>
        </div>
        <br />
        <p>
            <input type="submit" value="Cerrar" />
        </p>
    </fieldset>
}

<h5>
    @Html.ActionLink("Ir a principal", "Index")
    <span class="float-right">
        @Html.ActionLink("Atrás a elegir proyecto a cerrar", "Cierre")
    </span>
</h5>

Views/Home/Creacion.cshtml
@model Prototipos.Models.ViewModels.ProyectoView

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
    ViewBag.Title = "Creación";
}

<div class="title">
    <h1>@ViewBag.Title</h1>
    <h2>@ViewBag.Message</h2>
</div>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>

        @Html.HiddenFor(m => m.IdPrototipo)
        @Html.HiddenFor(m => m.FechaCreacion)
        @Html.HiddenFor(m => m.IdUsuarioCreador)
        @Html.HiddenFor(m => m.Estado)
        @Html.HiddenFor(m => m.FechaCierre)
        @Html.HiddenFor(m => m.IdUsuarioCierre)
        @Html.HiddenFor(m => m.Cierre)

        <div class="editor-label">
            @Html.LabelFor(model => model.Proyecto)
        </div>
        <div><i>Introducir nombre del proyecto</i></div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Proyecto)
            @Html.ValidationMessageFor(model => model.Proyecto)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Descripcion)
        </div>
        <div><i>Introducir descripción del proyecto</i></div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Descripcion)
            @Html.ValidationMessageFor(model => model.Descripcion)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Responsable)
        </div>
        <div><i>Introducir nombre del responsable de I+D del proyecto</i></div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Responsable, "ResponsableDropDown")
            @Html.ValidationMessageFor(model => model.Responsable)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Configuracion)
        </div>
        <div><i>Introducir la configuración inicial del montaje del prototipo</i></div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Configuracion)
            @Html.ValidationMessageFor(model => model.Configuracion)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Observaciones)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Observaciones)
            @Html.ValidationMessageFor(model => model.Observaciones)
        </div>
        <br />
        <p>
            <input type="submit" value="Crear" />
        </p>
    </fieldset>
}

<h5>
    @Html.ActionLink("Ir a principal", "Index")
</h5>

Views/Home/DeficienciaOk.cshtml
@{
    Layout = "~/Views/Shared/_Layout5.cshtml";
    ViewBag.Title = "Deficiencia creada con éxito";
    int idProy = ViewBag.idProy;
    int idFase = ViewBag.idFase;
}

<ul id="menuSubIndex">
    <li>@Html.ActionLink("Inicio gestión proyecto", "GestionProyecto", new { id = idProy })</li>
    <li>@Html.ActionLink("Inicio montaje", "Montaje", new { id = idProy })</li>
    <li class="selec">@Html.ActionLink("Puesta en marcha", "Marcha", new { id = idProy })</li>
    <li>@Html.ActionLink("Desmontaje", "Desmontaje", new { id = idProy })</li>
</ul>
<br />
<div class="center">
    <div class="titleOk">
        <h1>@ViewBag.Title</h1>
    </div>
</div>
<br />
<div class="message-aviso2">
    @ViewBag.AvisoMessage
</div>
<br /><br />
<div class="center">
    <table id="tablaSin">
        <tr>
            <td>
                <a href="@Url.Action("GestionProyecto", "Home", new { id = idProy })" class="button3">Volver a gestión proyecto</a>
            </td>
            <td>
                &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
            </td>
            <td>
                <a href="@Url.Action("NuevaDeficiencia", "Home", new {id = idFase })" class="button3">&nbsp Añadir más deficiencias &nbsp</a>
            </td>
        </tr> 
    </table>
    <br /><br /><br />
</div>